# Generated by Buildr 1.3.5, change to your liking
# Standard maven2 repository
repositories.remote << 'http://www.ibiblio.org/maven2'
repositories.remote << 'http://repo1.maven.org/maven2'
repositories.remote << 'http://wicketstuff.org/maven/repository/'

SERVLET_API = 'javax.servlet:servlet-api:jar:2.5'
SLF4J = transitive( 'org.slf4j:slf4j-log4j12:jar:1.5.6' )
WICKET = transitive( 'org.apache.wicket:wicket:jar:1.4.3' )
WICKET_EXT = transitive( 'org.apache.wicket:wicket-extensions:jar:1.4.3' )
WICKET_STUFF_ANNOT = transitive( 'org.wicketstuff:annotation:jar:1.4-SNAPSHOT' )
JODA = 'joda-time:joda-time:jar:1.6'

# Kryo
KRYO_SERIALIZERS = artifact( 'de.javakaffee:kryoserializers:jar:0.6' ).from(file('lib/kryo-serializers-0.6.jar'))
KRYO = artifact( 'com.esotericsoftware:kryo:jar:1.02' ).from( file( 'lib/kryo-1.02.jar' ) )
REFLECTASM = artifact('com.esotericsoftware:reflectasm:jar:0.8').from(file('lib/reflectasm-0.8.jar'))
MINLOG = artifact('com.esotericsoftware:minlog:jar:1.2').from(file('lib/minlog-1.2.jar'))
ASM = 'asm:asm:jar:3.2'
MSM_KRYO = artifact('de.javakaffee.web.msm:msm-kryo-serializer:jar:1.3.3').from(file('lib/msm-kryo-serializer-1.3.3.jar'))

# testing
JUNIT = 'junit:junit:jar:4.5'

desc 'memcached-session-manager benchmark webapp'
define 'msm-benchmark-webapp' do

  project.group = 'de.javakaffee.msm.bench'
  project.version = '1.0-SNAPSHOT'
  
  compile.with SERVLET_API, SLF4J, WICKET, WICKET_EXT, WICKET_STUFF_ANNOT, JODA
  
  test.with JUNIT
  test.using :testng
  
  package(:war).libs += artifacts(KRYO, REFLECTASM, MINLOG, ASM, KRYO_SERIALIZERS, MSM_KRYO)
  package :war, :id => 'msm-benchmark-webapp'
  
end
